<?php

use Illuminate\Database\Seeder;

class PartidosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('partidos')->insert(['id' => '1', 'provincia_id' => '1', 'nombre' => 'AZUL']);
        DB::table('partidos')->insert(['id' => '2', 'provincia_id' => '1', 'nombre' => 'PUAN']);
        DB::table('partidos')->insert(['id' => '4', 'provincia_id' => '1', 'nombre' => 'TIGRE']);
        DB::table('partidos')->insert(['id' => '5', 'provincia_id' => '1', 'nombre' => '25 DE MAYO']);
        DB::table('partidos')->insert(['id' => '6', 'provincia_id' => '1', 'nombre' => 'TRENQUE LAUQUEN']);
        DB::table('partidos')->insert(['id' => '7', 'provincia_id' => '1', 'nombre' => '9 DE JULIO']);
        DB::table('partidos')->insert(['id' => '8', 'provincia_id' => '1', 'nombre' => 'LANUS']);
        DB::table('partidos')->insert(['id' => '9', 'provincia_id' => '1', 'nombre' => 'LA PLATA']);
        DB::table('partidos')->insert(['id' => '10', 'provincia_id' => '1', 'nombre' => 'MONTE']);
        DB::table('partidos')->insert(['id' => '11', 'provincia_id' => '1', 'nombre' => 'PEHUAJO']);
        DB::table('partidos')->insert(['id' => '12', 'provincia_id' => '1', 'nombre' => 'SAN ISIDRO']);
        DB::table('partidos')->insert(['id' => '13', 'provincia_id' => '1', 'nombre' => 'PERGAMINO']);
        DB::table('partidos')->insert(['id' => '14', 'provincia_id' => '1', 'nombre' => 'ALBERTI']);
        DB::table('partidos')->insert(['id' => '15', 'provincia_id' => '1', 'nombre' => 'CHASCOMUS']);
        DB::table('partidos')->insert(['id' => '16', 'provincia_id' => '1', 'nombre' => 'ESTEBAN ECHEVERRIA']);
        DB::table('partidos')->insert(['id' => '17', 'provincia_id' => '1', 'nombre' => 'MERCEDES']);
        DB::table('partidos')->insert(['id' => '18', 'provincia_id' => '1', 'nombre' => 'BAHIA BLANCA']);
        DB::table('partidos')->insert(['id' => '19', 'provincia_id' => '1', 'nombre' => 'MERLO']);
        DB::table('partidos')->insert(['id' => '20', 'provincia_id' => '1', 'nombre' => 'JUNIN']);
        DB::table('partidos')->insert(['id' => '21', 'provincia_id' => '1', 'nombre' => 'GUAMINI']);
        DB::table('partidos')->insert(['id' => '22', 'provincia_id' => '1', 'nombre' => 'LUJAN']);
        DB::table('partidos')->insert(['id' => '23', 'provincia_id' => '1', 'nombre' => 'LEANDRO N.ALEM']);
        DB::table('partidos')->insert(['id' => '24', 'provincia_id' => '1', 'nombre' => 'LA MATANZA']);
        DB::table('partidos')->insert(['id' => '25', 'provincia_id' => '1', 'nombre' => 'GENERAL PAZ']);
        DB::table('partidos')->insert(['id' => '26', 'provincia_id' => '1', 'nombre' => 'SAN VICENTE']);
        DB::table('partidos')->insert(['id' => '27', 'provincia_id' => '1', 'nombre' => 'CAÑUELAS']);
        DB::table('partidos')->insert(['id' => '28', 'provincia_id' => '1', 'nombre' => 'ALMIRANTE BROWN']);
        DB::table('partidos')->insert(['id' => '29', 'provincia_id' => '1', 'nombre' => 'CNL.DE MARINA  L.ROSALES']);
        DB::table('partidos')->insert(['id' => '30', 'provincia_id' => '1', 'nombre' => 'BARADERO']);
        DB::table('partidos')->insert(['id' => '31', 'provincia_id' => '1', 'nombre' => 'SAAVEDRA']);
        DB::table('partidos')->insert(['id' => '32', 'provincia_id' => '1', 'nombre' => 'BRANDSEN']);
        DB::table('partidos')->insert(['id' => '33', 'provincia_id' => '1', 'nombre' => 'GENERAL SARMIENTO']);
        DB::table('partidos')->insert(['id' => '34', 'provincia_id' => '1', 'nombre' => 'TAPALQUE']);
        DB::table('partidos')->insert(['id' => '35', 'provincia_id' => '1', 'nombre' => 'SALADILLO']);
        DB::table('partidos')->insert(['id' => '36', 'provincia_id' => '1', 'nombre' => 'MAGDALENA']);
        DB::table('partidos')->insert(['id' => '37', 'provincia_id' => '1', 'nombre' => 'GONZALES CHAVES']);
        DB::table('partidos')->insert(['id' => '38', 'provincia_id' => '1', 'nombre' => 'GENERAL PINTO']);
        DB::table('partidos')->insert(['id' => '39', 'provincia_id' => '1', 'nombre' => 'NAVARRO']);
        DB::table('partidos')->insert(['id' => '40', 'provincia_id' => '1', 'nombre' => 'DAIREAUX']);
        DB::table('partidos')->insert(['id' => '41', 'provincia_id' => '1', 'nombre' => 'LOBOS']);
        DB::table('partidos')->insert(['id' => '42', 'provincia_id' => '1', 'nombre' => 'CORONEL DORREGO']);
        DB::table('partidos')->insert(['id' => '43', 'provincia_id' => '1', 'nombre' => 'ADOLFO ALSINA']);
        DB::table('partidos')->insert(['id' => '44', 'provincia_id' => '1', 'nombre' => 'COLON']);
        DB::table('partidos')->insert(['id' => '45', 'provincia_id' => '1', 'nombre' => 'GENERAL ARENALES']);
        DB::table('partidos')->insert(['id' => '46', 'provincia_id' => '1', 'nombre' => 'LINCOLN']);
        DB::table('partidos')->insert(['id' => '47', 'provincia_id' => '1', 'nombre' => 'VILLARINO']);
        DB::table('partidos')->insert(['id' => '48', 'provincia_id' => '1', 'nombre' => 'VICENTE LOPEZ']);
        DB::table('partidos')->insert(['id' => '49', 'provincia_id' => '1', 'nombre' => 'BARTOLOME MITRE']);
        DB::table('partidos')->insert(['id' => '50', 'provincia_id' => '1', 'nombre' => 'EXALTACION DE LA CRUZ']);
        DB::table('partidos')->insert(['id' => '51', 'provincia_id' => '1', 'nombre' => 'SALTO']);
        DB::table('partidos')->insert(['id' => '52', 'provincia_id' => '1', 'nombre' => 'BRAGADO']);
        DB::table('partidos')->insert(['id' => '53', 'provincia_id' => '1', 'nombre' => 'ZARATE']);
        DB::table('partidos')->insert(['id' => '54', 'provincia_id' => '1', 'nombre' => 'AVELLANEDA']);
        DB::table('partidos')->insert(['id' => '55', 'provincia_id' => '1', 'nombre' => 'AYACUCHO']);
        DB::table('partidos')->insert(['id' => '56', 'provincia_id' => '1', 'nombre' => 'SAN ANDRES DE GILES']);
        DB::table('partidos')->insert(['id' => '57', 'provincia_id' => '1', 'nombre' => 'TANDIL']);
        DB::table('partidos')->insert(['id' => '58', 'provincia_id' => '1', 'nombre' => 'RIVADAVIA']);
        DB::table('partidos')->insert(['id' => '59', 'provincia_id' => '1', 'nombre' => 'PATAGONES']);
        DB::table('partidos')->insert(['id' => '60', 'provincia_id' => '1', 'nombre' => 'GRL.VIAMONTE']);
        DB::table('partidos')->insert(['id' => '61', 'provincia_id' => '1', 'nombre' => 'CNL.DE MARINA LEONARDO ROSALES']);
        DB::table('partidos')->insert(['id' => '62', 'provincia_id' => '1', 'nombre' => 'BALCARCE']);
        DB::table('partidos')->insert(['id' => '63', 'provincia_id' => '1', 'nombre' => 'TRES ARROYOS']);
        DB::table('partidos')->insert(['id' => '64', 'provincia_id' => '1', 'nombre' => 'GENERAL VILLEGAS']);
        DB::table('partidos')->insert(['id' => '65', 'provincia_id' => '1', 'nombre' => 'LOMAS DE ZAMORA']);
        DB::table('partidos')->insert(['id' => '66', 'provincia_id' => '1', 'nombre' => 'BERISSO']);
        DB::table('partidos')->insert(['id' => '67', 'provincia_id' => '1', 'nombre' => 'JUAREZ']);
        DB::table('partidos')->insert(['id' => '68', 'provincia_id' => '1', 'nombre' => 'GRL.PUEYRREDON']);
        DB::table('partidos')->insert(['id' => '69', 'provincia_id' => '1', 'nombre' => 'CORONEL SUAREZ']);
        DB::table('partidos')->insert(['id' => '70', 'provincia_id' => '1', 'nombre' => 'ESCOBAR']);
        DB::table('partidos')->insert(['id' => '71', 'provincia_id' => '1', 'nombre' => 'CARLOS CASARES']);
        DB::table('partidos')->insert(['id' => '72', 'provincia_id' => '1', 'nombre' => 'CHIVILCOY']);
        DB::table('partidos')->insert(['id' => '73', 'provincia_id' => '1', 'nombre' => 'BERAZATEGUI']);
        DB::table('partidos')->insert(['id' => '74', 'provincia_id' => '1', 'nombre' => 'QUILMES']);
        DB::table('partidos')->insert(['id' => '75', 'provincia_id' => '1', 'nombre' => 'TORQUINST']);
        DB::table('partidos')->insert(['id' => '76', 'provincia_id' => '1', 'nombre' => '3 DE FEBRERO']);
        DB::table('partidos')->insert(['id' => '77', 'provincia_id' => '1', 'nombre' => 'OLAVARRIA']);
        DB::table('partidos')->insert(['id' => '78', 'provincia_id' => '1', 'nombre' => 'PELLEGRINI']);
        DB::table('partidos')->insert(['id' => '79', 'provincia_id' => '1', 'nombre' => 'GENERAL BELGANO']);
        DB::table('partidos')->insert(['id' => '80', 'provincia_id' => '1', 'nombre' => 'FLORENCIO VARELA']);
        DB::table('partidos')->insert(['id' => '81', 'provincia_id' => '1', 'nombre' => 'SALLIQUELO']);
        DB::table('partidos')->insert(['id' => '82', 'provincia_id' => '1', 'nombre' => 'CNL.DE MARINA L.ROSALES']);
        DB::table('partidos')->insert(['id' => '83', 'provincia_id' => '1', 'nombre' => 'MAR CHIQUITA']);
        DB::table('partidos')->insert(['id' => '84', 'provincia_id' => '1', 'nombre' => 'GENERAL PUEYRREDON']);
        DB::table('partidos')->insert(['id' => '85', 'provincia_id' => '1', 'nombre' => 'CAMPANA']);
        DB::table('partidos')->insert(['id' => '86', 'provincia_id' => '1', 'nombre' => 'GRL.SARMIENTO']);
        DB::table('partidos')->insert(['id' => '87', 'provincia_id' => '1', 'nombre' => 'ROJAS']);
        DB::table('partidos')->insert(['id' => '88', 'provincia_id' => '1', 'nombre' => 'SARMIENTO']);
        DB::table('partidos')->insert(['id' => '89', 'provincia_id' => '1', 'nombre' => 'CARMEN DE ARECO']);
        DB::table('partidos')->insert(['id' => '90', 'provincia_id' => '1', 'nombre' => 'PILA']);
        DB::table('partidos')->insert(['id' => '91', 'provincia_id' => '1', 'nombre' => 'TRES DE FEBRERO']);
        DB::table('partidos')->insert(['id' => '92', 'provincia_id' => '1', 'nombre' => 'MORON']);
        DB::table('partidos')->insert(['id' => '93', 'provincia_id' => '1', 'nombre' => 'CASTELLI']);
        DB::table('partidos')->insert(['id' => '94', 'provincia_id' => '1', 'nombre' => 'CHACABUCO']);
        DB::table('partidos')->insert(['id' => '95', 'provincia_id' => '1', 'nombre' => 'GENERAL VIAMONTE']);
        DB::table('partidos')->insert(['id' => '96', 'provincia_id' => '1', 'nombre' => 'RAUCH']);
        DB::table('partidos')->insert(['id' => '97', 'provincia_id' => '1', 'nombre' => 'GENERAL BELGRANO']);
        DB::table('partidos')->insert(['id' => '98', 'provincia_id' => '1', 'nombre' => 'TORNQUIST']);
        DB::table('partidos')->insert(['id' => '99', 'provincia_id' => '1', 'nombre' => 'NECOCHEA']);
        DB::table('partidos')->insert(['id' => '100', 'provincia_id' => '1', 'nombre' => 'MARCOS PAZ']);
        DB::table('partidos')->insert(['id' => '101', 'provincia_id' => '1', 'nombre' => 'CARLOS TEJEDOR']);
        DB::table('partidos')->insert(['id' => '102', 'provincia_id' => '1', 'nombre' => 'SAN PEDRO']);
        DB::table('partidos')->insert(['id' => '103', 'provincia_id' => '1', 'nombre' => 'GENERAL ALVARADO']);
        DB::table('partidos')->insert(['id' => '104', 'provincia_id' => '1', 'nombre' => 'SAN NICOLAS']);
        DB::table('partidos')->insert(['id' => '105', 'provincia_id' => '1', 'nombre' => 'HIPOLITO YRIGOYEN']);
        DB::table('partidos')->insert(['id' => '106', 'provincia_id' => '1', 'nombre' => 'LAS FLORES']);
        DB::table('partidos')->insert(['id' => '107', 'provincia_id' => '1', 'nombre' => 'CORONEL PRINGLES']);
        DB::table('partidos')->insert(['id' => '108', 'provincia_id' => '1', 'nombre' => 'GENERAL SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '109', 'provincia_id' => '1', 'nombre' => 'BENITO JUAREZ']);
        DB::table('partidos')->insert(['id' => '110', 'provincia_id' => '1', 'nombre' => 'SAN CAYETANO']);
        DB::table('partidos')->insert(['id' => '111', 'provincia_id' => '1', 'nombre' => 'ADOLFO GONZALES CHAVES']);
        DB::table('partidos')->insert(['id' => '112', 'provincia_id' => '1', 'nombre' => 'DOLORES']);
        DB::table('partidos')->insert(['id' => '113', 'provincia_id' => '1', 'nombre' => 'SAN ANTONIO']);
        DB::table('partidos')->insert(['id' => '114', 'provincia_id' => '1', 'nombre' => 'LOBERIA']);
        DB::table('partidos')->insert(['id' => '115', 'provincia_id' => '1', 'nombre' => 'RAMALLO']);
        DB::table('partidos')->insert(['id' => '116', 'provincia_id' => '1', 'nombre' => 'GENERAL ALVEAR']);
        DB::table('partidos')->insert(['id' => '117', 'provincia_id' => '1', 'nombre' => 'ENSENADA']);
        DB::table('partidos')->insert(['id' => '118', 'provincia_id' => '1', 'nombre' => 'TORDILLO']);
        DB::table('partidos')->insert(['id' => '119', 'provincia_id' => '1', 'nombre' => 'GENERAL GUIDO']);
        DB::table('partidos')->insert(['id' => '120', 'provincia_id' => '1', 'nombre' => 'GENERAL LAS HERAS']);
        DB::table('partidos')->insert(['id' => '121', 'provincia_id' => '1', 'nombre' => 'GENERAL JUAN MADARIAGA']);
        DB::table('partidos')->insert(['id' => '122', 'provincia_id' => '1', 'nombre' => 'GENERAL LA MADRID']);
        DB::table('partidos')->insert(['id' => '123', 'provincia_id' => '1', 'nombre' => 'GENERAL LAVALLE']);
        DB::table('partidos')->insert(['id' => '124', 'provincia_id' => '1', 'nombre' => 'GENERAL RODRIGUEZ']);
        DB::table('partidos')->insert(['id' => '125', 'provincia_id' => '1', 'nombre' => 'GENERAL VLLEGAS']);
        DB::table('partidos')->insert(['id' => '126', 'provincia_id' => '1', 'nombre' => 'ADOLFO GONZALEZ CHAVES']);
        DB::table('partidos')->insert(['id' => '127', 'provincia_id' => '1', 'nombre' => 'CORONEL DE MARINA L.ROSALES']);
        DB::table('partidos')->insert(['id' => '128', 'provincia_id' => '1', 'nombre' => 'BOLIVAR']);
        DB::table('partidos')->insert(['id' => '129', 'provincia_id' => '1', 'nombre' => 'SAN FERNANDO']);
        DB::table('partidos')->insert(['id' => '130', 'provincia_id' => '1', 'nombre' => 'CAPITAN SARMIENTO']);
        DB::table('partidos')->insert(['id' => '131', 'provincia_id' => '1', 'nombre' => 'ROQUE PEREZ']);
        DB::table('partidos')->insert(['id' => '132', 'provincia_id' => '1', 'nombre' => 'MORENO']);
        DB::table('partidos')->insert(['id' => '133', 'provincia_id' => '1', 'nombre' => 'LAPRIDA']);
        DB::table('partidos')->insert(['id' => '134', 'provincia_id' => '1', 'nombre' => 'MAIPU']);
        DB::table('partidos')->insert(['id' => '135', 'provincia_id' => '1', 'nombre' => 'ECHEVERRIA']);
        DB::table('partidos')->insert(['id' => '136', 'provincia_id' => '1', 'nombre' => 'PILAR']);
        DB::table('partidos')->insert(['id' => '137', 'provincia_id' => '1', 'nombre' => 'CORONEL DE MARINA L. ROSALES']);
        DB::table('partidos')->insert(['id' => '138', 'provincia_id' => '1', 'nombre' => 'SUIPACHA']);
        DB::table('partidos')->insert(['id' => '139', 'provincia_id' => '1', 'nombre' => 'SAN ANTONIO DE ARECO']);
        DB::table('partidos')->insert(['id' => '140', 'provincia_id' => '1', 'nombre' => 'BARAZATEGUI']);
        DB::table('partidos')->insert(['id' => '141', 'provincia_id' => '1', 'nombre' => 'ALSINA']);
        DB::table('partidos')->insert(['id' => '142', 'provincia_id' => '1', 'nombre' => 'LEANDRO N. ELEM']);
        DB::table('partidos')->insert(['id' => '143', 'provincia_id' => '1', 'nombre' => 'GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '144', 'provincia_id' => '1', 'nombre' => 'CORONEL']);
        DB::table('partidos')->insert(['id' => '145', 'provincia_id' => '2', 'nombre' => 'CAPAYAN']);
        DB::table('partidos')->insert(['id' => '146', 'provincia_id' => '2', 'nombre' => 'ANDALGALA']);
        DB::table('partidos')->insert(['id' => '147', 'provincia_id' => '2', 'nombre' => 'EL ALTO']);
        DB::table('partidos')->insert(['id' => '148', 'provincia_id' => '2', 'nombre' => 'SANTA ROSA']);
        DB::table('partidos')->insert(['id' => '149', 'provincia_id' => '2', 'nombre' => 'ANCASTI']);
        DB::table('partidos')->insert(['id' => '150', 'provincia_id' => '2', 'nombre' => 'PACLIN']);
        DB::table('partidos')->insert(['id' => '151', 'provincia_id' => '2', 'nombre' => 'SANTA MARIA']);
        DB::table('partidos')->insert(['id' => '152', 'provincia_id' => '2', 'nombre' => 'TINOGASTA']);
        DB::table('partidos')->insert(['id' => '153', 'provincia_id' => '2', 'nombre' => 'LA PAZ']);
        DB::table('partidos')->insert(['id' => '154', 'provincia_id' => '2', 'nombre' => 'VALLE VIEJO']);
        DB::table('partidos')->insert(['id' => '155', 'provincia_id' => '2', 'nombre' => 'ANTOFAGASTA DE LA SIERRA']);
        DB::table('partidos')->insert(['id' => '156', 'provincia_id' => '2', 'nombre' => 'BELEN']);
        DB::table('partidos')->insert(['id' => '158', 'provincia_id' => '2', 'nombre' => 'FRAY MAMERTO ESQUIU']);
        DB::table('partidos')->insert(['id' => '159', 'provincia_id' => '2', 'nombre' => 'POMAN']);
        DB::table('partidos')->insert(['id' => '160', 'provincia_id' => '2', 'nombre' => 'AMBATO']);
        DB::table('partidos')->insert(['id' => '161', 'provincia_id' => '3', 'nombre' => 'INDEPENDENCIA']);
        DB::table('partidos')->insert(['id' => '162', 'provincia_id' => '3', 'nombre' => 'SAN FERNANDO']);
        DB::table('partidos')->insert(['id' => '163', 'provincia_id' => '3', 'nombre' => 'PRIMERO DE MAYO']);
        DB::table('partidos')->insert(['id' => '164', 'provincia_id' => '3', 'nombre' => 'FRAY JUSTO SANTA MARIA DE ORO']);
        DB::table('partidos')->insert(['id' => '165', 'provincia_id' => '3', 'nombre' => 'SARGENTO CABRAL']);
        DB::table('partidos')->insert(['id' => '166', 'provincia_id' => '3', 'nombre' => 'GENERAL GUEMES']);
        DB::table('partidos')->insert(['id' => '167', 'provincia_id' => '3', 'nombre' => 'TAPENAGA']);
        DB::table('partidos')->insert(['id' => '168', 'provincia_id' => '3', 'nombre' => 'CHACABUCO']);
        DB::table('partidos')->insert(['id' => '169', 'provincia_id' => '3', 'nombre' => 'LIBERTADOR GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '170', 'provincia_id' => '3', 'nombre' => '25 DE MAYO']);
        DB::table('partidos')->insert(['id' => '171', 'provincia_id' => '3', 'nombre' => '12 DE OCTUBRE']);
        DB::table('partidos')->insert(['id' => '172', 'provincia_id' => '3', 'nombre' => 'COMANDANTE FERNANDEZ']);
        DB::table('partidos')->insert(['id' => '173', 'provincia_id' => '3', 'nombre' => 'QUITILIPI']);
        DB::table('partidos')->insert(['id' => '174', 'provincia_id' => '3', 'nombre' => 'MAYOR LUIS J.FONTANA']);
        DB::table('partidos')->insert(['id' => '175', 'provincia_id' => '3', 'nombre' => 'LIBERTAD']);
        DB::table('partidos')->insert(['id' => '176', 'provincia_id' => '3', 'nombre' => 'BERMEJO']);
        DB::table('partidos')->insert(['id' => '177', 'provincia_id' => '3', 'nombre' => 'ALMIRANTE BROWN']);
        DB::table('partidos')->insert(['id' => '178', 'provincia_id' => '3', 'nombre' => 'MEYOR LUIS J.FONTANA']);
        DB::table('partidos')->insert(['id' => '179', 'provincia_id' => '3', 'nombre' => 'GENERAL BELGRANO']);
        DB::table('partidos')->insert(['id' => '180', 'provincia_id' => '3', 'nombre' => 'LIBERTADOR GRL. SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '181', 'provincia_id' => '3', 'nombre' => 'GENERAL DONOVAN']);
        DB::table('partidos')->insert(['id' => '182', 'provincia_id' => '3', 'nombre' => 'SAN LORENZO']);
        DB::table('partidos')->insert(['id' => '183', 'provincia_id' => '3', 'nombre' => 'LEBERTADOR GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '184', 'provincia_id' => '3', 'nombre' => 'MAIPU']);
        DB::table('partidos')->insert(['id' => '185', 'provincia_id' => '3', 'nombre' => 'O\'HIGGINS']);
        DB::table('partidos')->insert(['id' => '186', 'provincia_id' => '3', 'nombre' => '9 DE JULIO']);
        DB::table('partidos')->insert(['id' => '187', 'provincia_id' => '3', 'nombre' => 'LIBERTADOR SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '188', 'provincia_id' => '4', 'nombre' => 'RIO SENGUERR']);
        DB::table('partidos')->insert(['id' => '189', 'provincia_id' => '4', 'nombre' => 'MARTIRES']);
        DB::table('partidos')->insert(['id' => '190', 'provincia_id' => '4', 'nombre' => 'ESCALANTE']);
        DB::table('partidos')->insert(['id' => '191', 'provincia_id' => '4', 'nombre' => 'GAIMAN']);
        DB::table('partidos')->insert(['id' => '192', 'provincia_id' => '4', 'nombre' => 'SARMIENTO']);
        DB::table('partidos')->insert(['id' => '193', 'provincia_id' => '4', 'nombre' => 'CUSHAMEN']);
        DB::table('partidos')->insert(['id' => '194', 'provincia_id' => '4', 'nombre' => 'FLORENTINO AMEGHINO']);
        DB::table('partidos')->insert(['id' => '195', 'provincia_id' => '4', 'nombre' => 'PASO DE INDIOS']);
        DB::table('partidos')->insert(['id' => '196', 'provincia_id' => '4', 'nombre' => 'TELSEN']);
        DB::table('partidos')->insert(['id' => '197', 'provincia_id' => '4', 'nombre' => 'LANGUIÑEO']);
        DB::table('partidos')->insert(['id' => '198', 'provincia_id' => '4', 'nombre' => 'GASTRE']);
        DB::table('partidos')->insert(['id' => '199', 'provincia_id' => '4', 'nombre' => 'FUTALEUFU']);
        DB::table('partidos')->insert(['id' => '200', 'provincia_id' => '4', 'nombre' => 'TEHUELCHES']);
        DB::table('partidos')->insert(['id' => '201', 'provincia_id' => '4', 'nombre' => 'RAWSON']);
        DB::table('partidos')->insert(['id' => '202', 'provincia_id' => '4', 'nombre' => 'BIEDMA']);
        DB::table('partidos')->insert(['id' => '203', 'provincia_id' => '5', 'nombre' => 'RIO CUARTO']);
        DB::table('partidos')->insert(['id' => '204', 'provincia_id' => '5', 'nombre' => 'TOTORAL']);
        DB::table('partidos')->insert(['id' => '205', 'provincia_id' => '5', 'nombre' => 'COLON']);
        DB::table('partidos')->insert(['id' => '206', 'provincia_id' => '5', 'nombre' => 'MINAS']);
        DB::table('partidos')->insert(['id' => '207', 'provincia_id' => '5', 'nombre' => 'PUNILLA']);
        DB::table('partidos')->insert(['id' => '208', 'provincia_id' => '5', 'nombre' => 'JUAREZ CELMAN']);
        DB::table('partidos')->insert(['id' => '209', 'provincia_id' => '5', 'nombre' => 'MARCOS JUAREZ']);
        DB::table('partidos')->insert(['id' => '210', 'provincia_id' => '5', 'nombre' => 'SAN JUSTO']);
        DB::table('partidos')->insert(['id' => '211', 'provincia_id' => '5', 'nombre' => 'TERCERO ARRIBA']);
        DB::table('partidos')->insert(['id' => '212', 'provincia_id' => '5', 'nombre' => 'RIO SECO']);
        DB::table('partidos')->insert(['id' => '213', 'provincia_id' => '5', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '214', 'provincia_id' => '5', 'nombre' => 'SANTA MARIA']);
        DB::table('partidos')->insert(['id' => '215', 'provincia_id' => '5', 'nombre' => 'SAN ALBERTO']);
        DB::table('partidos')->insert(['id' => '216', 'provincia_id' => '5', 'nombre' => 'UNION']);
        DB::table('partidos')->insert(['id' => '217', 'provincia_id' => '5', 'nombre' => 'POCHO']);
        DB::table('partidos')->insert(['id' => '218', 'provincia_id' => '5', 'nombre' => 'CALAMUCHITA']);
        DB::table('partidos')->insert(['id' => '219', 'provincia_id' => '5', 'nombre' => 'ISCHILIN']);
        DB::table('partidos')->insert(['id' => '220', 'provincia_id' => '5', 'nombre' => 'GENERAL SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '221', 'provincia_id' => '5', 'nombre' => 'RIO PRIMERO']);
        DB::table('partidos')->insert(['id' => '222', 'provincia_id' => '5', 'nombre' => 'CRUZ DEL EJE']);
        DB::table('partidos')->insert(['id' => '223', 'provincia_id' => '5', 'nombre' => 'GRL.ROCA']);
        DB::table('partidos')->insert(['id' => '224', 'provincia_id' => '5', 'nombre' => 'GENERAL ROCA']);
        DB::table('partidos')->insert(['id' => '225', 'provincia_id' => '5', 'nombre' => 'SOBREMONTE']);
        DB::table('partidos')->insert(['id' => '226', 'provincia_id' => '5', 'nombre' => 'RIO SEGUNDO']);
        DB::table('partidos')->insert(['id' => '227', 'provincia_id' => '5', 'nombre' => 'TULUMBA']);
        DB::table('partidos')->insert(['id' => '228', 'provincia_id' => '5', 'nombre' => 'SAN JAVIER']);
        DB::table('partidos')->insert(['id' => '229', 'provincia_id' => '5', 'nombre' => 'PRESIDENTE ROQUE SAEZ PEÑA']);
        DB::table('partidos')->insert(['id' => '230', 'provincia_id' => '5', 'nombre' => 'PRESIDENTE ROQUE SAENZ PEÑA']);
        DB::table('partidos')->insert(['id' => '232', 'provincia_id' => '5', 'nombre' => 'CRUZ DE EJE']);
        DB::table('partidos')->insert(['id' => '233', 'provincia_id' => '5', 'nombre' => 'CORONEL PRINGLES']);
        DB::table('partidos')->insert(['id' => '234', 'provincia_id' => '5', 'nombre' => 'RIO TERCERO']);
        DB::table('partidos')->insert(['id' => '235', 'provincia_id' => '5', 'nombre' => 'CVALAMUCHITA']);
        DB::table('partidos')->insert(['id' => '236', 'provincia_id' => '6', 'nombre' => 'SAN ROQUE']);
        DB::table('partidos')->insert(['id' => '237', 'provincia_id' => '6', 'nombre' => 'MONTE CASEROS']);
        DB::table('partidos')->insert(['id' => '238', 'provincia_id' => '6', 'nombre' => 'GENERAL ALVEAR']);
        DB::table('partidos')->insert(['id' => '239', 'provincia_id' => '6', 'nombre' => 'CURUZU CUATIA']);
        DB::table('partidos')->insert(['id' => '240', 'provincia_id' => '6', 'nombre' => 'SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '241', 'provincia_id' => '6', 'nombre' => 'MERCEDES']);
        DB::table('partidos')->insert(['id' => '242', 'provincia_id' => '6', 'nombre' => 'SALADAS']);
        DB::table('partidos')->insert(['id' => '243', 'provincia_id' => '6', 'nombre' => 'ITUZAINGO']);
        DB::table('partidos')->insert(['id' => '244', 'provincia_id' => '6', 'nombre' => 'BERON DE ASTRADA']);
        DB::table('partidos')->insert(['id' => '245', 'provincia_id' => '6', 'nombre' => 'BELLA VISTA']);
        DB::table('partidos')->insert(['id' => '246', 'provincia_id' => '6', 'nombre' => 'SAN LUIS DEL PALMAR']);
        DB::table('partidos')->insert(['id' => '247', 'provincia_id' => '6', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '248', 'provincia_id' => '6', 'nombre' => 'LAVALLE']);
        DB::table('partidos')->insert(['id' => '249', 'provincia_id' => '6', 'nombre' => 'PASO DE LOS LIBRES']);
        DB::table('partidos')->insert(['id' => '250', 'provincia_id' => '6', 'nombre' => 'GOYA']);
        DB::table('partidos')->insert(['id' => '251', 'provincia_id' => '6', 'nombre' => 'EMPEDRADO']);
        DB::table('partidos')->insert(['id' => '252', 'provincia_id' => '6', 'nombre' => 'SAUCE']);
        DB::table('partidos')->insert(['id' => '253', 'provincia_id' => '6', 'nombre' => 'GENERAL PAZ']);
        DB::table('partidos')->insert(['id' => '254', 'provincia_id' => '6', 'nombre' => 'SANTO TOME']);
        DB::table('partidos')->insert(['id' => '255', 'provincia_id' => '6', 'nombre' => 'SAN MIGUEL']);
        DB::table('partidos')->insert(['id' => '256', 'provincia_id' => '6', 'nombre' => 'CONCEPCION']);
        DB::table('partidos')->insert(['id' => '257', 'provincia_id' => '6', 'nombre' => 'ESQUINA']);
        DB::table('partidos')->insert(['id' => '258', 'provincia_id' => '6', 'nombre' => 'SAN COSME']);
        DB::table('partidos')->insert(['id' => '259', 'provincia_id' => '6', 'nombre' => 'ITATI']);
        DB::table('partidos')->insert(['id' => '260', 'provincia_id' => '6', 'nombre' => 'MBURUCUYA']);
        DB::table('partidos')->insert(['id' => '261', 'provincia_id' => '7', 'nombre' => 'URUGUAY']);
        DB::table('partidos')->insert(['id' => '262', 'provincia_id' => '7', 'nombre' => 'NOGOYA']);
        DB::table('partidos')->insert(['id' => '263', 'provincia_id' => '7', 'nombre' => 'TALA']);
        DB::table('partidos')->insert(['id' => '264', 'provincia_id' => '7', 'nombre' => 'GUALEGUAY']);
        DB::table('partidos')->insert(['id' => '265', 'provincia_id' => '7', 'nombre' => 'DIAMANTE']);
        DB::table('partidos')->insert(['id' => '266', 'provincia_id' => '7', 'nombre' => 'PARANA']);
        DB::table('partidos')->insert(['id' => '267', 'provincia_id' => '7', 'nombre' => 'GUALEGUAYCHU']);
        DB::table('partidos')->insert(['id' => '268', 'provincia_id' => '7', 'nombre' => 'COLON']);
        DB::table('partidos')->insert(['id' => '269', 'provincia_id' => '7', 'nombre' => 'VICTORIA']);
        DB::table('partidos')->insert(['id' => '270', 'provincia_id' => '7', 'nombre' => 'VILLAGUAY']);
        DB::table('partidos')->insert(['id' => '271', 'provincia_id' => '7', 'nombre' => 'FELICIANO']);
        DB::table('partidos')->insert(['id' => '272', 'provincia_id' => '7', 'nombre' => 'CONCORDIA']);
        DB::table('partidos')->insert(['id' => '273', 'provincia_id' => '7', 'nombre' => 'LA PAZ']);
        DB::table('partidos')->insert(['id' => '274', 'provincia_id' => '7', 'nombre' => 'FEDERACION']);
        DB::table('partidos')->insert(['id' => '275', 'provincia_id' => '7', 'nombre' => 'FEDERAL']);
        DB::table('partidos')->insert(['id' => '276', 'provincia_id' => '7', 'nombre' => 'CASTELLANOS']);
        DB::table('partidos')->insert(['id' => '277', 'provincia_id' => '8', 'nombre' => 'PILAGAS']);
        DB::table('partidos')->insert(['id' => '278', 'provincia_id' => '8', 'nombre' => 'PATIÑO']);
        DB::table('partidos')->insert(['id' => '279', 'provincia_id' => '8', 'nombre' => 'PILCOMAYO']);
        DB::table('partidos')->insert(['id' => '280', 'provincia_id' => '8', 'nombre' => 'BERMEJO']);
        DB::table('partidos')->insert(['id' => '281', 'provincia_id' => '8', 'nombre' => 'PIRANE']);
        DB::table('partidos')->insert(['id' => '282', 'provincia_id' => '8', 'nombre' => 'FORMOSA']);
        DB::table('partidos')->insert(['id' => '283', 'provincia_id' => '8', 'nombre' => 'MATACOS']);
        DB::table('partidos')->insert(['id' => '284', 'provincia_id' => '8', 'nombre' => 'RAMON LISTA']);
        DB::table('partidos')->insert(['id' => '285', 'provincia_id' => '8', 'nombre' => 'PILLAGAS']);
        DB::table('partidos')->insert(['id' => '286', 'provincia_id' => '8', 'nombre' => 'LAISHI']);
        DB::table('partidos')->insert(['id' => '287', 'provincia_id' => '9', 'nombre' => 'LEDESMA']);
        DB::table('partidos')->insert(['id' => '288', 'provincia_id' => '9', 'nombre' => 'COCHINOCA']);
        DB::table('partidos')->insert(['id' => '289', 'provincia_id' => '9', 'nombre' => 'EL CARMEN']);
        DB::table('partidos')->insert(['id' => '290', 'provincia_id' => '9', 'nombre' => 'TUMBAYA']);
        DB::table('partidos')->insert(['id' => '291', 'provincia_id' => '9', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '292', 'provincia_id' => '9', 'nombre' => 'YAVI']);
        DB::table('partidos')->insert(['id' => '293', 'provincia_id' => '9', 'nombre' => 'HUMAHUACA']);
        DB::table('partidos')->insert(['id' => '294', 'provincia_id' => '9', 'nombre' => 'RINCONADA']);
        DB::table('partidos')->insert(['id' => '295', 'provincia_id' => '9', 'nombre' => 'VALLE GRANDE']);
        DB::table('partidos')->insert(['id' => '296', 'provincia_id' => '9', 'nombre' => 'SUSQUES']);
        DB::table('partidos')->insert(['id' => '297', 'provincia_id' => '9', 'nombre' => 'SANTA CATALINA']);
        DB::table('partidos')->insert(['id' => '298', 'provincia_id' => '9', 'nombre' => 'SAN ANTONIO']);
        DB::table('partidos')->insert(['id' => '299', 'provincia_id' => '9', 'nombre' => 'SANTA BARBARA']);
        DB::table('partidos')->insert(['id' => '300', 'provincia_id' => '9', 'nombre' => 'SAN PEDRO']);
        DB::table('partidos')->insert(['id' => '301', 'provincia_id' => '9', 'nombre' => 'TILCARA']);
        DB::table('partidos')->insert(['id' => '302', 'provincia_id' => '9', 'nombre' => 'LADESMA']);
        DB::table('partidos')->insert(['id' => '303', 'provincia_id' => '10', 'nombre' => 'HUCAL']);
        DB::table('partidos')->insert(['id' => '304', 'provincia_id' => '10', 'nombre' => 'REALICO']);
        DB::table('partidos')->insert(['id' => '305', 'provincia_id' => '10', 'nombre' => 'MARA CO']);
        DB::table('partidos')->insert(['id' => '306', 'provincia_id' => '10', 'nombre' => 'QUEMUQUEMU']);
        DB::table('partidos')->insert(['id' => '307', 'provincia_id' => '10', 'nombre' => 'CHICAL CO']);
        DB::table('partidos')->insert(['id' => '308', 'provincia_id' => '10', 'nombre' => 'GUATRACHE']);
        DB::table('partidos')->insert(['id' => '309', 'provincia_id' => '10', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '310', 'provincia_id' => '10', 'nombre' => 'CALEUCALEU']);
        DB::table('partidos')->insert(['id' => '311', 'provincia_id' => '10', 'nombre' => 'TRENEL']);
        DB::table('partidos')->insert(['id' => '312', 'provincia_id' => '10', 'nombre' => 'UTRACAN']);
        DB::table('partidos')->insert(['id' => '313', 'provincia_id' => '10', 'nombre' => 'ATREUCO']);
        DB::table('partidos')->insert(['id' => '314', 'provincia_id' => '10', 'nombre' => 'TOAY']);
        DB::table('partidos')->insert(['id' => '315', 'provincia_id' => '10', 'nombre' => 'CHAPADLEUFU']);
        DB::table('partidos')->insert(['id' => '316', 'provincia_id' => '10', 'nombre' => 'CONELO']);
        DB::table('partidos')->insert(['id' => '317', 'provincia_id' => '10', 'nombre' => 'PUELEN']);
        DB::table('partidos')->insert(['id' => '318', 'provincia_id' => '10', 'nombre' => 'RANCUL']);
        DB::table('partidos')->insert(['id' => '319', 'provincia_id' => '10', 'nombre' => 'QUEMU QUEMU']);
        DB::table('partidos')->insert(['id' => '320', 'provincia_id' => '10', 'nombre' => 'LOVENTUE']);
        DB::table('partidos')->insert(['id' => '321', 'provincia_id' => '10', 'nombre' => 'CONHELO']);
        DB::table('partidos')->insert(['id' => '322', 'provincia_id' => '10', 'nombre' => 'CATRILO']);
        DB::table('partidos')->insert(['id' => '323', 'provincia_id' => '10', 'nombre' => 'CHAPALEUFU']);
        DB::table('partidos')->insert(['id' => '324', 'provincia_id' => '10', 'nombre' => 'ULTRACAN']);
        DB::table('partidos')->insert(['id' => '325', 'provincia_id' => '10', 'nombre' => 'CHALILEO']);
        DB::table('partidos')->insert(['id' => '326', 'provincia_id' => '10', 'nombre' => 'LIHUEL CALEL']);
        DB::table('partidos')->insert(['id' => '327', 'provincia_id' => '10', 'nombre' => 'MARACO']);
        DB::table('partidos')->insert(['id' => '328', 'provincia_id' => '10', 'nombre' => 'CALEU CALEU']);
        DB::table('partidos')->insert(['id' => '329', 'provincia_id' => '10', 'nombre' => 'CURACO']);
        DB::table('partidos')->insert(['id' => '330', 'provincia_id' => '10', 'nombre' => 'LIMAY MAHUIDA']);
        DB::table('partidos')->insert(['id' => '331', 'provincia_id' => '11', 'nombre' => 'CASTRO BARROS']);
        DB::table('partidos')->insert(['id' => '332', 'provincia_id' => '11', 'nombre' => 'GENERAL SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '333', 'provincia_id' => '11', 'nombre' => 'GENERAL LAVALLE']);
        DB::table('partidos')->insert(['id' => '334', 'provincia_id' => '11', 'nombre' => 'ARAUCO']);
        DB::table('partidos')->insert(['id' => '335', 'provincia_id' => '11', 'nombre' => 'GRAL.ANGEL V.PEÑALOZA']);
        DB::table('partidos')->insert(['id' => '336', 'provincia_id' => '11', 'nombre' => 'SAN BLAS DE LOS SAUCES']);
        DB::table('partidos')->insert(['id' => '337', 'provincia_id' => '11', 'nombre' => 'INDEPENDENCIA']);
        DB::table('partidos')->insert(['id' => '338', 'provincia_id' => '11', 'nombre' => 'GENERAL OCAMPO']);
        DB::table('partidos')->insert(['id' => '339', 'provincia_id' => '11', 'nombre' => 'CHILECITO']);
        DB::table('partidos')->insert(['id' => '340', 'provincia_id' => '11', 'nombre' => 'FAMATINA']);
        DB::table('partidos')->insert(['id' => '341', 'provincia_id' => '11', 'nombre' => 'GRL.JUAN FACUNDO QUIROGA']);
        DB::table('partidos')->insert(['id' => '342', 'provincia_id' => '11', 'nombre' => 'GRL.ANGEL V. PEÑALOZA']);
        DB::table('partidos')->insert(['id' => '343', 'provincia_id' => '11', 'nombre' => 'GENERAL BELGRANO']);
        DB::table('partidos')->insert(['id' => '344', 'provincia_id' => '11', 'nombre' => 'GENERAL SARMIENTO']);
        DB::table('partidos')->insert(['id' => '345', 'provincia_id' => '11', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '346', 'provincia_id' => '11', 'nombre' => 'GDOR. GORDILLO']);
        DB::table('partidos')->insert(['id' => '347', 'provincia_id' => '11', 'nombre' => 'GENERAL ANGEL VICENTE PEÑALOZA']);
        DB::table('partidos')->insert(['id' => '348', 'provincia_id' => '11', 'nombre' => 'GOBERNADOR GORDILLO']);
        DB::table('partidos')->insert(['id' => '349', 'provincia_id' => '11', 'nombre' => 'ROSARIO VERA PEÑALOZA']);
        DB::table('partidos')->insert(['id' => '350', 'provincia_id' => '11', 'nombre' => 'GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '351', 'provincia_id' => '11', 'nombre' => 'GENERAL LA MADRID']);
        DB::table('partidos')->insert(['id' => '352', 'provincia_id' => '11', 'nombre' => 'GENERAL JUAN FACUNDO QUIROGA']);
        DB::table('partidos')->insert(['id' => '353', 'provincia_id' => '11', 'nombre' => 'GENERALOCAMPO']);
        DB::table('partidos')->insert(['id' => '354', 'provincia_id' => '11', 'nombre' => 'SANAGASTA']);
        DB::table('partidos')->insert(['id' => '355', 'provincia_id' => '12', 'nombre' => 'SAN RAFAEL']);
        DB::table('partidos')->insert(['id' => '356', 'provincia_id' => '12', 'nombre' => 'LUJAN']);
        DB::table('partidos')->insert(['id' => '357', 'provincia_id' => '12', 'nombre' => 'MALARGUE']);
        DB::table('partidos')->insert(['id' => '358', 'provincia_id' => '12', 'nombre' => 'GUAYMALLEN']);
        DB::table('partidos')->insert(['id' => '359', 'provincia_id' => '12', 'nombre' => 'LAVALLE']);
        DB::table('partidos')->insert(['id' => '360', 'provincia_id' => '12', 'nombre' => 'JUNIN']);
        DB::table('partidos')->insert(['id' => '361', 'provincia_id' => '12', 'nombre' => 'TUPUNGATO']);
        DB::table('partidos')->insert(['id' => '362', 'provincia_id' => '12', 'nombre' => 'RIVADAVIA']);
        DB::table('partidos')->insert(['id' => '363', 'provincia_id' => '12', 'nombre' => 'MAIPU']);
        DB::table('partidos')->insert(['id' => '364', 'provincia_id' => '12', 'nombre' => 'GODOY CRUZ']);
        DB::table('partidos')->insert(['id' => '365', 'provincia_id' => '12', 'nombre' => 'GENERAL ALVEAR']);
        DB::table('partidos')->insert(['id' => '366', 'provincia_id' => '12', 'nombre' => 'LA PAZ']);
        DB::table('partidos')->insert(['id' => '367', 'provincia_id' => '12', 'nombre' => 'TUNUYAN']);
        DB::table('partidos')->insert(['id' => '368', 'provincia_id' => '12', 'nombre' => 'SAN CARLOS']);
        DB::table('partidos')->insert(['id' => '369', 'provincia_id' => '12', 'nombre' => 'LAS HERAS']);
        DB::table('partidos')->insert(['id' => '370', 'provincia_id' => '12', 'nombre' => 'LUJAN DE CUYO']);
        DB::table('partidos')->insert(['id' => '371', 'provincia_id' => '12', 'nombre' => 'SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '372', 'provincia_id' => '12', 'nombre' => 'SANTA ROSA']);
        DB::table('partidos')->insert(['id' => '373', 'provincia_id' => '12', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '374', 'provincia_id' => '13', 'nombre' => '25 DE MAYO']);
        DB::table('partidos')->insert(['id' => '375', 'provincia_id' => '13', 'nombre' => 'IGUAZU']);
        DB::table('partidos')->insert(['id' => '376', 'provincia_id' => '13', 'nombre' => 'EL DORADO']);
        DB::table('partidos')->insert(['id' => '377', 'provincia_id' => '13', 'nombre' => 'LEANDRO N. ALEM']);
        DB::table('partidos')->insert(['id' => '378', 'provincia_id' => '13', 'nombre' => 'APOSTOLES']);
        DB::table('partidos')->insert(['id' => '379', 'provincia_id' => '13', 'nombre' => 'CAINGUAS']);
        DB::table('partidos')->insert(['id' => '380', 'provincia_id' => '13', 'nombre' => 'LEANDRO N.ALEM']);
        DB::table('partidos')->insert(['id' => '381', 'provincia_id' => '13', 'nombre' => 'CONCEPCION']);
        DB::table('partidos')->insert(['id' => '382', 'provincia_id' => '13', 'nombre' => 'SAN PEDRO']);
        DB::table('partidos')->insert(['id' => '383', 'provincia_id' => '13', 'nombre' => 'CANDELARIA']);
        DB::table('partidos')->insert(['id' => '384', 'provincia_id' => '13', 'nombre' => 'GRL.MANUEL BELGRANO']);
        DB::table('partidos')->insert(['id' => '385', 'provincia_id' => '13', 'nombre' => 'OBERA']);
        DB::table('partidos')->insert(['id' => '386', 'provincia_id' => '13', 'nombre' => 'LIBERTADOR GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '387', 'provincia_id' => '13', 'nombre' => 'SAN IGNACIO']);
        DB::table('partidos')->insert(['id' => '388', 'provincia_id' => '13', 'nombre' => 'MONTECARLO']);
        DB::table('partidos')->insert(['id' => '389', 'provincia_id' => '13', 'nombre' => 'GENERAL MANUEL BELGRANO']);
        DB::table('partidos')->insert(['id' => '390', 'provincia_id' => '13', 'nombre' => 'LEBERTADOR GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '391', 'provincia_id' => '13', 'nombre' => 'EL GUARANI']);
        DB::table('partidos')->insert(['id' => '392', 'provincia_id' => '13', 'nombre' => 'ELDORADO']);
        DB::table('partidos')->insert(['id' => '393', 'provincia_id' => '13', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '394', 'provincia_id' => '13', 'nombre' => 'GUARANI']);
        DB::table('partidos')->insert(['id' => '395', 'provincia_id' => '13', 'nombre' => 'SAN JAVIER']);
        DB::table('partidos')->insert(['id' => '396', 'provincia_id' => '13', 'nombre' => 'LIBERTADOR GRL. SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '397', 'provincia_id' => '14', 'nombre' => 'COLLON CURA']);
        DB::table('partidos')->insert(['id' => '398', 'provincia_id' => '14', 'nombre' => 'ALUMINE']);
        DB::table('partidos')->insert(['id' => '399', 'provincia_id' => '14', 'nombre' => 'MINAS']);
        DB::table('partidos')->insert(['id' => '400', 'provincia_id' => '14', 'nombre' => 'AÑELO']);
        DB::table('partidos')->insert(['id' => '401', 'provincia_id' => '14', 'nombre' => 'CONFLUENCIA']);
        DB::table('partidos')->insert(['id' => '402', 'provincia_id' => '14', 'nombre' => 'CHOS MALAL']);
        DB::table('partidos')->insert(['id' => '403', 'provincia_id' => '14', 'nombre' => 'PICUNCHES']);
        DB::table('partidos')->insert(['id' => '404', 'provincia_id' => '14', 'nombre' => 'NORQUIN']);
        DB::table('partidos')->insert(['id' => '405', 'provincia_id' => '14', 'nombre' => 'PEHUENCHES']);
        DB::table('partidos')->insert(['id' => '406', 'provincia_id' => '14', 'nombre' => 'LONCOPUE']);
        DB::table('partidos')->insert(['id' => '407', 'provincia_id' => '14', 'nombre' => 'HUILICHES']);
        DB::table('partidos')->insert(['id' => '408', 'provincia_id' => '14', 'nombre' => 'ZAPALA']);
        DB::table('partidos')->insert(['id' => '409', 'provincia_id' => '14', 'nombre' => 'CATAN LIL']);
        DB::table('partidos')->insert(['id' => '410', 'provincia_id' => '14', 'nombre' => 'ÑORQUIN']);
        DB::table('partidos')->insert(['id' => '411', 'provincia_id' => '14', 'nombre' => 'LOS LAGOS']);
        DB::table('partidos')->insert(['id' => '412', 'provincia_id' => '14', 'nombre' => 'PICUN LEUFU']);
        DB::table('partidos')->insert(['id' => '413', 'provincia_id' => '14', 'nombre' => 'LACAR']);
        DB::table('partidos')->insert(['id' => '414', 'provincia_id' => '14', 'nombre' => 'ÑOEQUIN']);
        DB::table('partidos')->insert(['id' => '415', 'provincia_id' => '15', 'nombre' => 'VALCHETA']);
        DB::table('partidos')->insert(['id' => '416', 'provincia_id' => '15', 'nombre' => '25 DE MAYO']);
        DB::table('partidos')->insert(['id' => '417', 'provincia_id' => '15', 'nombre' => 'EL CUY']);
        DB::table('partidos')->insert(['id' => '418', 'provincia_id' => '15', 'nombre' => 'ÑORQUINCO']);
        DB::table('partidos')->insert(['id' => '419', 'provincia_id' => '15', 'nombre' => 'GENERAL ROCA']);
        DB::table('partidos')->insert(['id' => '420', 'provincia_id' => '15', 'nombre' => 'AVELLANEDA']);
        DB::table('partidos')->insert(['id' => '421', 'provincia_id' => '15', 'nombre' => 'CONESA']);
        DB::table('partidos')->insert(['id' => '422', 'provincia_id' => '15', 'nombre' => 'PICHI MAHUIDA']);
        DB::table('partidos')->insert(['id' => '423', 'provincia_id' => '15', 'nombre' => 'SAN ANTONIO']);
        DB::table('partidos')->insert(['id' => '424', 'provincia_id' => '15', 'nombre' => 'PILCANIYEU']);
        DB::table('partidos')->insert(['id' => '425', 'provincia_id' => '15', 'nombre' => '9 DE JULIO']);
        DB::table('partidos')->insert(['id' => '426', 'provincia_id' => '15', 'nombre' => 'ADOLFO ALSINA']);
        DB::table('partidos')->insert(['id' => '427', 'provincia_id' => '15', 'nombre' => 'BARILOCHE']);
        DB::table('partidos')->insert(['id' => '428', 'provincia_id' => '15', 'nombre' => 'PIHI MAHUIDA']);
        DB::table('partidos')->insert(['id' => '429', 'provincia_id' => '16', 'nombre' => 'LA VIÑA']);
        DB::table('partidos')->insert(['id' => '430', 'provincia_id' => '16', 'nombre' => 'SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '431', 'provincia_id' => '16', 'nombre' => 'ORAN']);
        DB::table('partidos')->insert(['id' => '432', 'provincia_id' => '16', 'nombre' => 'ANTA']);
        DB::table('partidos')->insert(['id' => '433', 'provincia_id' => '16', 'nombre' => 'GRAL.JOSE DE SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '434', 'provincia_id' => '16', 'nombre' => 'GUACHIPAS']);
        DB::table('partidos')->insert(['id' => '435', 'provincia_id' => '16', 'nombre' => 'ROSARIO DE LA FRONTERA']);
        DB::table('partidos')->insert(['id' => '436', 'provincia_id' => '16', 'nombre' => 'RIVADAVIA']);
        DB::table('partidos')->insert(['id' => '437', 'provincia_id' => '16', 'nombre' => 'METAN']);
        DB::table('partidos')->insert(['id' => '438', 'provincia_id' => '16', 'nombre' => 'SAN CARLOS']);
        DB::table('partidos')->insert(['id' => '439', 'provincia_id' => '16', 'nombre' => 'GRL.GUEMES']);
        DB::table('partidos')->insert(['id' => '440', 'provincia_id' => '16', 'nombre' => 'CACHI']);
        DB::table('partidos')->insert(['id' => '441', 'provincia_id' => '16', 'nombre' => 'ROSARIO DE LERMA']);
        DB::table('partidos')->insert(['id' => '442', 'provincia_id' => '16', 'nombre' => 'CAFAYATE']);
        DB::table('partidos')->insert(['id' => '443', 'provincia_id' => '16', 'nombre' => 'LOS ANDES']);
        DB::table('partidos')->insert(['id' => '444', 'provincia_id' => '16', 'nombre' => 'GRL.JOSE DE SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '445', 'provincia_id' => '16', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '446', 'provincia_id' => '16', 'nombre' => 'GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '447', 'provincia_id' => '16', 'nombre' => 'GENERAL GUEMES']);
        DB::table('partidos')->insert(['id' => '448', 'provincia_id' => '16', 'nombre' => 'CERRILLOS']);
        DB::table('partidos')->insert(['id' => '449', 'provincia_id' => '16', 'nombre' => 'CHICOANA']);
        DB::table('partidos')->insert(['id' => '450', 'provincia_id' => '16', 'nombre' => 'LA POMA']);
        DB::table('partidos')->insert(['id' => '451', 'provincia_id' => '16', 'nombre' => 'LA CAPITAL']);
        DB::table('partidos')->insert(['id' => '452', 'provincia_id' => '16', 'nombre' => 'CANDELARIA']);
        DB::table('partidos')->insert(['id' => '453', 'provincia_id' => '16', 'nombre' => 'ROSARIO']);
        DB::table('partidos')->insert(['id' => '454', 'provincia_id' => '16', 'nombre' => 'IRUYA']);
        DB::table('partidos')->insert(['id' => '455', 'provincia_id' => '16', 'nombre' => 'LA CALDERA']);
        DB::table('partidos')->insert(['id' => '456', 'provincia_id' => '16', 'nombre' => 'LOA ANDES']);
        DB::table('partidos')->insert(['id' => '457', 'provincia_id' => '16', 'nombre' => 'MOLINOS']);
        DB::table('partidos')->insert(['id' => '458', 'provincia_id' => '16', 'nombre' => 'SANTA VICTORIA']);
        DB::table('partidos')->insert(['id' => '459', 'provincia_id' => '17', 'nombre' => '9 DE JULIO']);
        DB::table('partidos')->insert(['id' => '460', 'provincia_id' => '17', 'nombre' => 'JACHAL']);
        DB::table('partidos')->insert(['id' => '461', 'provincia_id' => '17', 'nombre' => 'ALBARDON']);
        DB::table('partidos')->insert(['id' => '462', 'provincia_id' => '17', 'nombre' => '25 DE MAYO']);
        DB::table('partidos')->insert(['id' => '463', 'provincia_id' => '17', 'nombre' => 'SANTA LUCIA']);
        DB::table('partidos')->insert(['id' => '464', 'provincia_id' => '17', 'nombre' => 'ANGACO']);
        DB::table('partidos')->insert(['id' => '465', 'provincia_id' => '17', 'nombre' => 'IGLESIA']);
        DB::table('partidos')->insert(['id' => '466', 'provincia_id' => '17', 'nombre' => 'VALLE FERTIL']);
        DB::table('partidos')->insert(['id' => '467', 'provincia_id' => '17', 'nombre' => 'CALINGASTA']);
        DB::table('partidos')->insert(['id' => '468', 'provincia_id' => '17', 'nombre' => 'RIVADAVIA']);
        DB::table('partidos')->insert(['id' => '469', 'provincia_id' => '17', 'nombre' => 'CAUCETE']);
        DB::table('partidos')->insert(['id' => '470', 'provincia_id' => '17', 'nombre' => 'SARMIENTO']);
        DB::table('partidos')->insert(['id' => '471', 'provincia_id' => '17', 'nombre' => 'POCITO']);
        DB::table('partidos')->insert(['id' => '472', 'provincia_id' => '17', 'nombre' => 'SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '473', 'provincia_id' => '17', 'nombre' => 'CHIMBAS']);
        DB::table('partidos')->insert(['id' => '474', 'provincia_id' => '17', 'nombre' => 'IGLESIAS']);
        DB::table('partidos')->insert(['id' => '475', 'provincia_id' => '17', 'nombre' => 'ULLUN']);
        DB::table('partidos')->insert(['id' => '476', 'provincia_id' => '17', 'nombre' => 'RAWSON']);
        DB::table('partidos')->insert(['id' => '477', 'provincia_id' => '17', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '478', 'provincia_id' => '17', 'nombre' => 'ZONDA']);
        DB::table('partidos')->insert(['id' => '479', 'provincia_id' => '18', 'nombre' => 'BELGRANO']);
        DB::table('partidos')->insert(['id' => '480', 'provincia_id' => '18', 'nombre' => 'CHACABUCO']);
        DB::table('partidos')->insert(['id' => '481', 'provincia_id' => '18', 'nombre' => 'LA CAPITAL']);
        DB::table('partidos')->insert(['id' => '482', 'provincia_id' => '18', 'nombre' => 'GOBERNADOR DUPUY']);
        DB::table('partidos')->insert(['id' => '483', 'provincia_id' => '18', 'nombre' => 'GRL.PEDERNERA']);
        DB::table('partidos')->insert(['id' => '484', 'provincia_id' => '18', 'nombre' => 'AYACUCHO']);
        DB::table('partidos')->insert(['id' => '485', 'provincia_id' => '18', 'nombre' => 'JUNIN']);
        DB::table('partidos')->insert(['id' => '486', 'provincia_id' => '18', 'nombre' => 'GONERNADOR DUPUY']);
        DB::table('partidos')->insert(['id' => '487', 'provincia_id' => '18', 'nombre' => 'CORONEL PRINGLES']);
        DB::table('partidos')->insert(['id' => '488', 'provincia_id' => '18', 'nombre' => 'GENERAL PEDERNERA']);
        DB::table('partidos')->insert(['id' => '489', 'provincia_id' => '18', 'nombre' => 'GOBERNADOR DUVAL']);
        DB::table('partidos')->insert(['id' => '490', 'provincia_id' => '18', 'nombre' => 'IGLESIA']);
        DB::table('partidos')->insert(['id' => '491', 'provincia_id' => '18', 'nombre' => 'LIBERTADOR GRL. SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '492', 'provincia_id' => '18', 'nombre' => 'LIBERTADOR GRL.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '493', 'provincia_id' => '18', 'nombre' => 'LIBERTADOR GR.SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '494', 'provincia_id' => '18', 'nombre' => 'CAUCETE']);
        DB::table('partidos')->insert(['id' => '495', 'provincia_id' => '19', 'nombre' => 'GUER AIKE']);
        DB::table('partidos')->insert(['id' => '496', 'provincia_id' => '19', 'nombre' => 'DESEADO']);
        DB::table('partidos')->insert(['id' => '497', 'provincia_id' => '19', 'nombre' => 'RIO CHICO']);
        DB::table('partidos')->insert(['id' => '498', 'provincia_id' => '19', 'nombre' => 'MAGALLANES']);
        DB::table('partidos')->insert(['id' => '499', 'provincia_id' => '19', 'nombre' => 'LAGO ARGENTINO']);
        DB::table('partidos')->insert(['id' => '500', 'provincia_id' => '19', 'nombre' => 'CORPEN AIKE']);
        DB::table('partidos')->insert(['id' => '501', 'provincia_id' => '19', 'nombre' => 'LAGO BUENOS AIRES']);
        DB::table('partidos')->insert(['id' => '502', 'provincia_id' => '20', 'nombre' => 'GENERAL LOPEZ']);
        DB::table('partidos')->insert(['id' => '503', 'provincia_id' => '20', 'nombre' => 'ROSARIO']);
        DB::table('partidos')->insert(['id' => '504', 'provincia_id' => '20', 'nombre' => 'GENERAL OBLIGADO']);
        DB::table('partidos')->insert(['id' => '505', 'provincia_id' => '20', 'nombre' => 'CONSTITUCION']);
        DB::table('partidos')->insert(['id' => '506', 'provincia_id' => '20', 'nombre' => 'SAN LORENZO']);
        DB::table('partidos')->insert(['id' => '507', 'provincia_id' => '20', 'nombre' => 'SAN JAVIER']);
        DB::table('partidos')->insert(['id' => '508', 'provincia_id' => '20', 'nombre' => 'LA CAPITAL']);
        DB::table('partidos')->insert(['id' => '509', 'provincia_id' => '20', 'nombre' => 'SAN CRISTOBAL']);
        DB::table('partidos')->insert(['id' => '510', 'provincia_id' => '20', 'nombre' => 'IRIONDO']);
        DB::table('partidos')->insert(['id' => '511', 'provincia_id' => '20', 'nombre' => 'CASTELLANOS']);
        DB::table('partidos')->insert(['id' => '512', 'provincia_id' => '20', 'nombre' => 'NUEVE DE JULIO']);
        DB::table('partidos')->insert(['id' => '513', 'provincia_id' => '20', 'nombre' => 'CASEROS']);
        DB::table('partidos')->insert(['id' => '514', 'provincia_id' => '20', 'nombre' => 'SAN JERONIMO']);
        DB::table('partidos')->insert(['id' => '515', 'provincia_id' => '20', 'nombre' => 'BELGRANO']);
        DB::table('partidos')->insert(['id' => '516', 'provincia_id' => '20', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '517', 'provincia_id' => '20', 'nombre' => 'SAN JUSTO']);
        DB::table('partidos')->insert(['id' => '518', 'provincia_id' => '20', 'nombre' => 'GRL.OBLIGADO']);
        DB::table('partidos')->insert(['id' => '519', 'provincia_id' => '20', 'nombre' => 'LA CAPUTAL']);
        DB::table('partidos')->insert(['id' => '520', 'provincia_id' => '20', 'nombre' => 'GRL.LOPEZ']);
        DB::table('partidos')->insert(['id' => '521', 'provincia_id' => '20', 'nombre' => 'VERA']);
        DB::table('partidos')->insert(['id' => '522', 'provincia_id' => '20', 'nombre' => '9 DE JULIO']);
        DB::table('partidos')->insert(['id' => '523', 'provincia_id' => '20', 'nombre' => 'SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '524', 'provincia_id' => '20', 'nombre' => 'LAS COLONIAS']);
        DB::table('partidos')->insert(['id' => '525', 'provincia_id' => '20', 'nombre' => 'GARAY']);
        DB::table('partidos')->insert(['id' => '526', 'provincia_id' => '20', 'nombre' => 'CASTELANOS']);
        DB::table('partidos')->insert(['id' => '527', 'provincia_id' => '20', 'nombre' => 'LAS COLINAS']);
        DB::table('partidos')->insert(['id' => '528', 'provincia_id' => '21', 'nombre' => 'BANDA']);
        DB::table('partidos')->insert(['id' => '529', 'provincia_id' => '21', 'nombre' => 'MORENO']);
        DB::table('partidos')->insert(['id' => '530', 'provincia_id' => '21', 'nombre' => 'ALBERDI']);
        DB::table('partidos')->insert(['id' => '531', 'provincia_id' => '21', 'nombre' => 'PELLEGRINI']);
        DB::table('partidos')->insert(['id' => '532', 'provincia_id' => '21', 'nombre' => 'OJO DE AGUA']);
        DB::table('partidos')->insert(['id' => '533', 'provincia_id' => '21', 'nombre' => 'RIO HONDO']);
        DB::table('partidos')->insert(['id' => '534', 'provincia_id' => '21', 'nombre' => 'GENERAL TABOADA']);
        DB::table('partidos')->insert(['id' => '535', 'provincia_id' => '21', 'nombre' => 'CHOYA']);
        DB::table('partidos')->insert(['id' => '536', 'provincia_id' => '21', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '537', 'provincia_id' => '21', 'nombre' => 'AGUIRRE']);
        DB::table('partidos')->insert(['id' => '538', 'provincia_id' => '21', 'nombre' => 'SILIPICA']);
        DB::table('partidos')->insert(['id' => '539', 'provincia_id' => '21', 'nombre' => 'BELGRANO']);
        DB::table('partidos')->insert(['id' => '540', 'provincia_id' => '21', 'nombre' => 'FIGUEROA']);
        DB::table('partidos')->insert(['id' => '541', 'provincia_id' => '21', 'nombre' => 'SALAVINA']);
        DB::table('partidos')->insert(['id' => '542', 'provincia_id' => '21', 'nombre' => 'QUEBRACHOS']);
        DB::table('partidos')->insert(['id' => '543', 'provincia_id' => '21', 'nombre' => 'ROBLES']);
        DB::table('partidos')->insert(['id' => '544', 'provincia_id' => '21', 'nombre' => 'AVELLANEDA']);
        DB::table('partidos')->insert(['id' => '545', 'provincia_id' => '21', 'nombre' => 'JIMENEZ']);
        DB::table('partidos')->insert(['id' => '546', 'provincia_id' => '21', 'nombre' => 'ATAMISQUI']);
        DB::table('partidos')->insert(['id' => '547', 'provincia_id' => '21', 'nombre' => 'SAN MARTIN']);
        DB::table('partidos')->insert(['id' => '548', 'provincia_id' => '21', 'nombre' => 'MATARA']);
        DB::table('partidos')->insert(['id' => '549', 'provincia_id' => '21', 'nombre' => 'SALAYINA']);
        DB::table('partidos')->insert(['id' => '550', 'provincia_id' => '21', 'nombre' => 'GUASAYAN']);
        DB::table('partidos')->insert(['id' => '551', 'provincia_id' => '21', 'nombre' => 'COPO']);
        DB::table('partidos')->insert(['id' => '552', 'provincia_id' => '21', 'nombre' => 'BRIGADIER JUAN FELIPE IBARRA']);
        DB::table('partidos')->insert(['id' => '553', 'provincia_id' => '21', 'nombre' => 'DOBLES']);
        DB::table('partidos')->insert(['id' => '554', 'provincia_id' => '21', 'nombre' => 'SARMIENTO']);
        DB::table('partidos')->insert(['id' => '555', 'provincia_id' => '21', 'nombre' => 'LORETO']);
        DB::table('partidos')->insert(['id' => '556', 'provincia_id' => '21', 'nombre' => 'MITRE']);
        DB::table('partidos')->insert(['id' => '557', 'provincia_id' => '21', 'nombre' => 'RIVADAVIA']);
        DB::table('partidos')->insert(['id' => '558', 'provincia_id' => '22', 'nombre' => 'USHUAIA']);
        DB::table('partidos')->insert(['id' => '559', 'provincia_id' => '22', 'nombre' => 'ISLAS DEL ATLANTICO SUR']);
        DB::table('partidos')->insert(['id' => '560', 'provincia_id' => '22', 'nombre' => 'SECTOR ANTARTICO ARGENTINO']);
        DB::table('partidos')->insert(['id' => '561', 'provincia_id' => '22', 'nombre' => 'RIO GRANDE']);
        DB::table('partidos')->insert(['id' => '562', 'provincia_id' => '22', 'nombre' => 'IS.DEL ATLANTICO SUR E IS.MALVINAS']);
        DB::table('partidos')->insert(['id' => '563', 'provincia_id' => '22', 'nombre' => 'ANTARTIDA ARGENTINA']);
        DB::table('partidos')->insert(['id' => '564', 'provincia_id' => '23', 'nombre' => 'BURRUYACU']);
        DB::table('partidos')->insert(['id' => '565', 'provincia_id' => '23', 'nombre' => 'TRANCAS']);
        DB::table('partidos')->insert(['id' => '566', 'provincia_id' => '23', 'nombre' => 'MONTEROS']);
        DB::table('partidos')->insert(['id' => '567', 'provincia_id' => '23', 'nombre' => 'LEALES']);
        DB::table('partidos')->insert(['id' => '568', 'provincia_id' => '23', 'nombre' => 'CRUZ ALTA']);
        DB::table('partidos')->insert(['id' => '569', 'provincia_id' => '23', 'nombre' => 'RIO CHICO']);
        DB::table('partidos')->insert(['id' => '570', 'provincia_id' => '23', 'nombre' => 'CHICLIGASTA']);
        DB::table('partidos')->insert(['id' => '571', 'provincia_id' => '23', 'nombre' => 'TAFI']);
        DB::table('partidos')->insert(['id' => '572', 'provincia_id' => '23', 'nombre' => 'GRANEROS']);
        DB::table('partidos')->insert(['id' => '573', 'provincia_id' => '23', 'nombre' => 'FAMAILLA']);
        DB::table('partidos')->insert(['id' => '574', 'provincia_id' => '23', 'nombre' => 'CAPITAL']);
        DB::table('partidos')->insert(['id' => '575', 'provincia_id' => '24', 'nombre' => 'CAPITAL FEDERAL']);
    }
}
